package com.ireaserch.pojo;

import java.io.Serializable;

/**
 * Model class of 百度洞察.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TBaiduInsight implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 自增id. */
	private Integer id;

	/** 洞察ID. */
	private Integer crowdId;

	/** 日程. */
	private Integer scheduleId;

	/** 日程状态. */
	private Integer scheduleStatus;

	/** json结果. */
	private String jsonResult;

	/** excel结果. */
	private String excelResult;

	/** 用户ID. */
	private Integer userId;

	/**
	 * Constructor.
	 */
	public TBaiduInsight() {
	}

	/**
	 * Set the 自增id.
	 * 
	 * @param id
	 *            自增id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the 自增id.
	 * 
	 * @return 自增id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 洞察ID.
	 * 
	 * @param crowdId
	 *            洞察ID
	 */
	public void setCrowdId(Integer crowdId) {
		this.crowdId = crowdId;
	}

	/**
	 * Get the 洞察ID.
	 * 
	 * @return 洞察ID
	 */
	public Integer getCrowdId() {
		return this.crowdId;
	}

	/**
	 * Set the 日程.
	 * 
	 * @param scheduleId
	 *            日程
	 */
	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	/**
	 * Get the 日程.
	 * 
	 * @return 日程
	 */
	public Integer getScheduleId() {
		return this.scheduleId;
	}

	/**
	 * Set the 日程状态.
	 * 
	 * @param scheduleStatus
	 *            日程状态
	 */
	public void setScheduleStatus(Integer scheduleStatus) {
		this.scheduleStatus = scheduleStatus;
	}

	/**
	 * Get the 日程状态.
	 * 
	 * @return 日程状态
	 */
	public Integer getScheduleStatus() {
		return this.scheduleStatus;
	}

	/**
	 * Set the json结果.
	 * 
	 * @param jsonResult
	 *            json结果
	 */
	public void setJsonResult(String jsonResult) {
		this.jsonResult = jsonResult;
	}

	/**
	 * Get the json结果.
	 * 
	 * @return json结果
	 */
	public String getJsonResult() {
		return this.jsonResult;
	}

	/**
	 * Set the excel结果.
	 * 
	 * @param excelResult
	 *            excel结果
	 */
	public void setExcelResult(String excelResult) {
		this.excelResult = excelResult;
	}

	/**
	 * Get the excel结果.
	 * 
	 * @return excel结果
	 */
	public String getExcelResult() {
		return this.excelResult;
	}

	/**
	 * Set the 用户ID.
	 * 
	 * @param userId
	 *            用户ID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the 用户ID.
	 * 
	 * @return 用户ID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TBaiduInsight other = (TBaiduInsight) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
