package com.ireaserch.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 洞察表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TCrowd implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 自增id. */
	private Integer id;

	/** 创建时间. */
	private Date createTime;

	/** 洞察名称. */
	private String crowdName;

	/** 洞察来源. */
	private Integer crowdSource;

	/** 查询类型. */
	private String queryType;

	/** APP名称. */
	private String appName;

	/** 手机品牌. */
	private String mobileBrand;

	/** 数量. */
	private Long quantity;

	/** 活力. */
	private Integer vitality;

	/** 开始时间. */
	private Date timeBegin;

	/** 结束时间. */
	private Date timeEnd;

	/** 描述. */
	private String description;

	/** 上传文件. */
	private String uploadFile;

	/** 用户ID. */
	private Integer userId;

	/** generate_file. */
	private String generateFile;

	/** 洞察状态. */
	private Integer crowdStatus;

	/**
	 * Constructor.
	 */
	public TCrowd() {
	}

	/**
	 * Set the 自增id.
	 * 
	 * @param id
	 *            自增id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the 自增id.
	 * 
	 * @return 自增id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 洞察名称.
	 * 
	 * @param crowdName
	 *            洞察名称
	 */
	public void setCrowdName(String crowdName) {
		this.crowdName = crowdName;
	}

	/**
	 * Get the 洞察名称.
	 * 
	 * @return 洞察名称
	 */
	public String getCrowdName() {
		return this.crowdName;
	}

	/**
	 * Set the 洞察来源.
	 * 
	 * @param crowdSource
	 *            洞察来源
	 */
	public void setCrowdSource(Integer crowdSource) {
		this.crowdSource = crowdSource;
	}

	/**
	 * Get the 洞察来源.
	 * 
	 * @return 洞察来源
	 */
	public Integer getCrowdSource() {
		return this.crowdSource;
	}

	/**
	 * Set the 查询类型.
	 * 
	 * @param queryType
	 *            查询类型
	 */
	public void setQueryType(String queryType) {
		this.queryType = queryType;
	}

	/**
	 * Get the 查询类型.
	 * 
	 * @return 查询类型
	 */
	public String getQueryType() {
		return this.queryType;
	}

	/**
	 * Set the APP名称.
	 * 
	 * @param appName
	 *            APP名称
	 */
	public void setAppName(String appName) {
		this.appName = appName;
	}

	/**
	 * Get the APP名称.
	 * 
	 * @return APP名称
	 */
	public String getAppName() {
		return this.appName;
	}

	/**
	 * Set the 手机品牌.
	 * 
	 * @param mobileBrand
	 *            手机品牌
	 */
	public void setMobileBrand(String mobileBrand) {
		this.mobileBrand = mobileBrand;
	}

	/**
	 * Get the 手机品牌.
	 * 
	 * @return 手机品牌
	 */
	public String getMobileBrand() {
		return this.mobileBrand;
	}

	/**
	 * Set the 数量.
	 * 
	 * @param quantity
	 *            数量
	 */
	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	/**
	 * Get the 数量.
	 * 
	 * @return 数量
	 */
	public Long getQuantity() {
		return this.quantity;
	}

	/**
	 * Set the 活力.
	 * 
	 * @param vitality
	 *            活力
	 */
	public void setVitality(Integer vitality) {
		this.vitality = vitality;
	}

	/**
	 * Get the 活力.
	 * 
	 * @return 活力
	 */
	public Integer getVitality() {
		return this.vitality;
	}

	/**
	 * Set the 开始时间.
	 * 
	 * @param timeBegin
	 *            开始时间
	 */
	public void setTimeBegin(Date timeBegin) {
		this.timeBegin = timeBegin;
	}

	/**
	 * Get the 开始时间.
	 * 
	 * @return 开始时间
	 */
	public Date getTimeBegin() {
		return this.timeBegin;
	}

	/**
	 * Set the 结束时间.
	 * 
	 * @param timeEnd
	 *            结束时间
	 */
	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	/**
	 * Get the 结束时间.
	 * 
	 * @return 结束时间
	 */
	public Date getTimeEnd() {
		return this.timeEnd;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param description
	 *            描述
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 上传文件.
	 * 
	 * @param uploadFile
	 *            上传文件
	 */
	public void setUploadFile(String uploadFile) {
		this.uploadFile = uploadFile;
	}

	/**
	 * Get the 上传文件.
	 * 
	 * @return 上传文件
	 */
	public String getUploadFile() {
		return this.uploadFile;
	}

	/**
	 * Set the 用户ID.
	 * 
	 * @param userId
	 *            用户ID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the 用户ID.
	 * 
	 * @return 用户ID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the generate_file.
	 * 
	 * @param generateFile
	 *            generate_file
	 */
	public void setGenerateFile(String generateFile) {
		this.generateFile = generateFile;
	}

	/**
	 * Get the generate_file.
	 * 
	 * @return generate_file
	 */
	public String getGenerateFile() {
		return this.generateFile;
	}

	/**
	 * Set the 洞察状态.
	 * 
	 * @param crowdStatus
	 *            洞察状态
	 */
	public void setCrowdStatus(Integer crowdStatus) {
		this.crowdStatus = crowdStatus;
	}

	/**
	 * Get the 洞察状态.
	 * 
	 * @return 洞察状态
	 */
	public Integer getCrowdStatus() {
		return this.crowdStatus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TCrowd other = (TCrowd) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
