package com.ireaserch.pojo;

import java.io.Serializable;

/**
 * Model class of mac月度重复移除表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TMonthlyMacDuplicateRemoval implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 自增id. */
	private Integer id;

	/** 年份. */
	private Integer year;

	/** 月份. */
	private Integer month;

	/** mac数量. */
	private Long macCount;

	/**
	 * Constructor.
	 */
	public TMonthlyMacDuplicateRemoval() {
	}

	/**
	 * Set the 自增id.
	 * 
	 * @param id
	 *            自增id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the 自增id.
	 * 
	 * @return 自增id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 年份.
	 * 
	 * @param year
	 *            年份
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * Get the 年份.
	 * 
	 * @return 年份
	 */
	public Integer getYear() {
		return this.year;
	}

	/**
	 * Set the 月份.
	 * 
	 * @param month
	 *            月份
	 */
	public void setMonth(Integer month) {
		this.month = month;
	}

	/**
	 * Get the 月份.
	 * 
	 * @return 月份
	 */
	public Integer getMonth() {
		return this.month;
	}

	/**
	 * Set the mac数量.
	 * 
	 * @param macCount
	 *            mac数量
	 */
	public void setMacCount(Long macCount) {
		this.macCount = macCount;
	}

	/**
	 * Get the mac数量.
	 * 
	 * @return mac数量
	 */
	public Long getMacCount() {
		return this.macCount;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TMonthlyMacDuplicateRemoval other = (TMonthlyMacDuplicateRemoval) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
