package com.ireaserch.pojo;

import java.io.Serializable;

/**
 * Model class of 用户表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TUser implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 自增id. */
	private Integer id;

	/** 用户名. */
	private String username;

	/** 密码. */
	private String password;

	/** 昵称. */
	private String nickname;

	/** gender. */
	private Integer gender;

	/** 公司. */
	private String company;

	/** 邮箱. */
	private String email;

	/** 出生年份. */
	private Integer birthYear;

	/** 出生月份. */
	private Integer birthMonth;

	/** 出生日期. */
	private Integer birthDay;

	/**
	 * Constructor.
	 */
	public TUser() {
	}

	/**
	 * Set the 自增id.
	 * 
	 * @param id
	 *            自增id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the 自增id.
	 * 
	 * @return 自增id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param username
	 *            用户名
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Set the 密码.
	 * 
	 * @param password
	 *            密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 密码.
	 * 
	 * @return 密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 昵称.
	 * 
	 * @param nickname
	 *            昵称
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * Get the 昵称.
	 * 
	 * @return 昵称
	 */
	public String getNickname() {
		return this.nickname;
	}

	/**
	 * Set the gender.
	 * 
	 * @param gender
	 *            gender
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * Get the gender.
	 * 
	 * @return gender
	 */
	public Integer getGender() {
		return this.gender;
	}

	/**
	 * Set the 公司.
	 * 
	 * @param company
	 *            公司
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/**
	 * Get the 公司.
	 * 
	 * @return 公司
	 */
	public String getCompany() {
		return this.company;
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 出生年份.
	 * 
	 * @param birthYear
	 *            出生年份
	 */
	public void setBirthYear(Integer birthYear) {
		this.birthYear = birthYear;
	}

	/**
	 * Get the 出生年份.
	 * 
	 * @return 出生年份
	 */
	public Integer getBirthYear() {
		return this.birthYear;
	}

	/**
	 * Set the 出生月份.
	 * 
	 * @param birthMonth
	 *            出生月份
	 */
	public void setBirthMonth(Integer birthMonth) {
		this.birthMonth = birthMonth;
	}

	/**
	 * Get the 出生月份.
	 * 
	 * @return 出生月份
	 */
	public Integer getBirthMonth() {
		return this.birthMonth;
	}

	/**
	 * Set the 出生日期.
	 * 
	 * @param birthDay
	 *            出生日期
	 */
	public void setBirthDay(Integer birthDay) {
		this.birthDay = birthDay;
	}

	/**
	 * Get the 出生日期.
	 * 
	 * @return 出生日期
	 */
	public Integer getBirthDay() {
		return this.birthDay;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TUser other = (TUser) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
