package com.ireaserch.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of mac周重复移除表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TWeeklyMacDuplicateRemoval implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** 计数日期. */
	private Date countDate;

	/** mac数量. */
	private Long macCount;

	/**
	 * Constructor.
	 */
	public TWeeklyMacDuplicateRemoval() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 计数日期.
	 * 
	 * @param countDate
	 *            计数日期
	 */
	public void setCountDate(Date countDate) {
		this.countDate = countDate;
	}

	/**
	 * Get the 计数日期.
	 * 
	 * @return 计数日期
	 */
	public Date getCountDate() {
		return this.countDate;
	}

	/**
	 * Set the mac数量.
	 * 
	 * @param macCount
	 *            mac数量
	 */
	public void setMacCount(Long macCount) {
		this.macCount = macCount;
	}

	/**
	 * Get the mac数量.
	 * 
	 * @return mac数量
	 */
	public Long getMacCount() {
		return this.macCount;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TWeeklyMacDuplicateRemoval other = (TWeeklyMacDuplicateRemoval) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
